### ISSUE TITLE
Optimize/Refactor test suite

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/laravel-translatable#75]
* [x] upgrade test code base to current standard #73 
* [x] optimize test classes performance and readability
  * [x] `LocalesTest` #77 
  * [x] `ScopesTest` #86
  * [x] `TestCoreModelExtension` #87
  * [x] `TranslatableTest` #84 
  * [x] `ValidationTest` #88 
* [x] Remove temp `TestsBase` class #81 
* [x] Remove `tests/seeds` folder #89 
* [x] reduce amount of models to the absolute minimum #101
* [x] use `namespace Astrotomic\Translatable\Tests` for tests #100 
* [x] use `static::` instead of `$this->` for assertions #91 
* [x] set `void` return type for all test methods #92
* [x] move to TravisCI instead of CircleCI #83
* [x] use sqlite in local environment (default) use MySQL in CI #83
* [x] Add @Lloople to package credits #82

**Comment by Lloople** [comment]
I'm doing the 1 and 2 right now 👍 After all is working again we can replace the Country examples with Food. Better leave the current assertions for the moment I think

**Comment by Gummibeer** [comment]
Have updated the initial comment. It could be that I will add further tasks. They are kind of sorted. So if you go from top to bottom they shouldn't conflict this much and are sorted by priority/importance. I just list everything that is related to the testsuite and should get improved.

**Comment by Lloople** [comment]
Awesome! I'll do `LocalesTest` next 👍

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.6.0
